### ISSUE TITLE
~/.profile is ignored

### ISSUE THREAD

**Issue by PieFaceThrowsPie** [EndeavourOS-Community-Editions/sway#20] opened 2021-12-28 00:47 UTC
Upon install, both a ~/.bash_profile and ~/.profile were created, which caused bash to ignore ~/.profile and the environment variables inside.
Deleting ~/.bash_profile resolved the issue.

From the bash man page:

> it first reads and executes commands from the file /etc/profile, if that file exists. After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable.

**Comment by OdiousImp2604** [comment] 2021-12-31 12:25
Thank you very much. This is a problem we have been struggling for a long time. 

I will share with the rest of the team.

Thank You.

**Comment by killajoe** [comment] 2022-01-17 11:15
~/.config/environment.d/envvars.conf
can be used also for the needed envs.

**Comment by killajoe** [comment] 2022-02-13 22:00
is this solved now and tested to work as it should????

**Comment by Korriee** [comment] 2022-04-02 16:18
Hi joe,
not solved. this drove me crazy for awhile since FF was using xwayland even though the var was set in ~/.profile lol
from what i understand if ~/.bash_profile exists ~/.bash_login & ~/.profile won't be checked.
https://nanxiao.me/en/why-doesnt-profile-take-effect-in-arch-linux/ did a great writeup on it & i can confirm that adding 
[[ -f ~/.profile ]] && . ~/.profile into my ~/.bash_profile did make ~/.profile work - although i'm not entirely sure if there's any negatives to doing this or what they are. Maybe someone more experienced can advise.
Thanks

**Comment by OdiousImp2604** [comment] 2022-04-15 10:51
Closing. It appears to work fine with the lastest iso release.

**Closed by OdiousImp2604** 2022-04-15 10:51 UTC
Labels: good first issue
